### ISSUE TITLE
Strip all browser cookies before forwarding requests

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#102]
It seems like some of the browser cookies are forwarded to the backend services where they might be used to authenticate API requests instead of the oAuth access token. This might lead to unexpected results.

**Comment by jirikuncar** [comment]
closed via #112 - https://github.com/SwissDataScienceCenter/renku-gateway/blob/master/helm-chart/renku-gateway/templates/configmap.yaml#L48-L50
