### ISSUE TITLE
Fix forwarding of logger.info() logging in k8s

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-gateway#106]
All of the `logger.info()` logging is missing in the k8s logs while `logger.debug()` logs are present. This can lead to situations where the gateway pod is dying without leaving any logs at all.

----
Original description by @rokroskar: 
At the moment, there are no logs provided when things go wrong during bootstrapping of the gateway. For example, if keycloak isn't reachable, there is no message just an unresponsive service. This makes debugging of new deployments difficult.

**Comment by ableuler** [comment]
There *is* logging at startup, but some of the logging (not just at startup) seems to be suppressed by k8s.
