### ISSUE TITLE
Call to create webhook sends no or invalid oauth token

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-gateway#107]
It looks at in some circumstances when Gatway does the POST to webhook-services' `/projects/:id/webhooks` it does send `OAUTH-TOKEN` header with some invalid token. We tried a few tests on the UI-team environment and when we did curl webhook-services' endpoint from its container console it works properly. So effectively these two calls where succeeding while failing with 401 from gitlab, when the same endpoint was hit by the Gateway.

`curl -XPOST --header "OAUTH-TOKEN: 07fbaa9b39f0e208ab1cf48a819888dfe8740613cbd25bc0d2cb58700872e874" http://localhost:9001/projects/72/webhooks/validation -v`

`curl -XPOST --header "OAUTH-TOKEN: 07fbaa9b39f0e208ab1cf48a819888dfe8740613cbd25bc0d2cb58700872e874" http://localhost:9001/projects/72/webhooks -v`

**Comment by lorenzo-cavazzi** [comment]
Using the latest version of `renku-graph` I can query the webhook-services endpoint using the Oauth token, but when the Bearer token is set it doesn't work anymore. I add 2 explicit examples using pods in my namespace

Working
```
curl -XPOST --header "OAUTH-TOKEN: 4027e87f6a63a69ecf478a6792e8ae84a50959e0f8366567e0b7336c90e614e6" http://lorenzo-renku-graph-webhook-service/projects/72/webhooks/validation -v
```

Not working
```
curl -XPOST --header "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJWQjhuYmZhZ2Jpbmo0TjNKS1BzdTE2dHlXdTcxcU5IaGVwLXducHRDeExzIn0.eyJqdGkiOiI3ODMwZWQ2NC01ODJkLTQ4YmYtYjY2ZS05ZjU5ZmIxNzRjOTEiLCJleHAiOjE1NTMwMTIxNzgsIm5iZiI6MCwiaWF0IjoxNTUzMDEwMzc4LCJpc3MiOiJodHRwczovL2xvcmVuem8uZGV2LnJlbmt1LmNoL2F1dGgvcmVhbG1zL1Jlbmt1IiwiYXVkIjoiZ2F0ZXdheSIsInN1YiI6IjBmMjY3MDBkLWQwMmItNDJiMi04NmMwLTE2NGU5OWQwODdjNiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImdhdGV3YXkiLCJhdXRoX3RpbWUiOjE1NTMwMTAzNzgsInNlc3Npb25fc3RhdGUiOiIwNjgwMzQyNi1jZmRiLTQ1YzEtYjBlOS04ZGE3NDBlYjg2ZTkiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vbG9yZW56by5kZXYucmVua3UuY2gvKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJGaXJzdCBMYXN0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoibm9lbWFpbEBub2UubWFpbCIsImdpdmVuX25hbWUiOiJGaXJzdCIsImZhbWlseV9uYW1lIjoiTGFzdCIsImVtYWlsIjoibm9lbWFpbEBub2UubWFpbCJ9.W3aaSTjOVUrXsKMt1Ae58Q9M9KyDHjUdj7t6VBKhe0KWs2eezkSixmN8bWTrhZH6mbjqZEmSOCBhlzErRnpTUoHLq6YD_c7s16YksvsbMk1tOuHvjNCIyS2InTg-4Nbkl56XC_GqhmWFs7YX8WddG7bwGeTmK9xqMESHNXuIpNtL0g7ZidgD9gsegsKYc7AqZFrHbsBJ0PknJghd8h15BXp7EOk0iLyolpXE7ZqiXQw7sJdRa2LIftCrqRqMNuJDdU0Fy-gg2BUdL4fqhbVbOFaWSFUtMRFr9lBvmi8g5ak2YVAobAFz06C7wu5DAX8tFO1DuqgmGfEUeie0pvoevw" http://lorenzo-renku-graph-webhook-service/projects/72/webhooks/validation -v
```

**Comment by jachro** [comment]
As far as can I see the `Bearer` token is quite different from the `OAUTH-TOKEN` and Graph Services expects the same tokens regardless sent as `Bearer` or in `OAUTH-TOKEN`. Of course, the `Bearer` is the preferred way of authorising the call and once Gateway uses `Bearer` please could you raise an issue on `renku-graph` so I remove support for `OAUTH-TOKEN`.
Thanks
Kuba
