### ISSUE TITLE
Gateway to relay `GET <renku>/datasets/:id` to `GET /knowledge-graph/datasets/:id`

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-gateway#168]
As a Renku owner, I'd like Gateway to redirect requests to `GET <renku>/datasets/:id` to `GET http://knowledge-graph/knowledge-graph/datasets/:id`.

For the reasoning of the change look here: https://app.zenhub.com/workspaces/renku-platform-5d259f8758ce4031eea0908c/issues/swissdatasciencecenter/renku-gateway/169

**Comment by ableuler** [comment]
Closing in favour of #174 and #175.
