### ISSUE TITLE
Gateway to relay `GET <renku>/users/:id` to `GET /knowledge-graph/users/:id`

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-gateway#170]
As a Renku owner, I'd like Gateway to relay requests to GET <renku>/users/:id to GET http://knowledge-graph/knowledge-graph/users/:id.

For the reasoning of the change look here: https://app.zenhub.com/workspaces/renku-platform-5d259f8758ce4031eea0908c/issues/swissdatasciencecenter/renku-gateway/169

**Comment by ableuler** [comment]
Are you sure you also want to handle users? Why not use the users from keycloak or potentially even gitlab?

**Comment by ableuler** [comment]
Closing in favour of #174 and #175.
