### ISSUE TITLE
Set up content-based redirections

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#174]
Requests to URIs identifying a Renku entity should be routed to the gateway and then result in a redirection to the UI page or the corresponding API endpoint depending on the `Accept` header.

- [x] Modify ingress rule to serve gateway also under the ~Renku base URL~ `/entities`.
- [x] Add two routers based on header rules each combined with a redirectRegex middleware to achieve the 
```
text/html -> UI
application/json or application/ld+json -> API
```
redirections.

See also the discussion on https://github.com/SwissDataScienceCenter/renku-gateway/issues/169 for details.

**Comment by lorenzo-cavazzi** [comment]
In renku-notebook we have a few (well at least one) APIs that return `text/plain`. If it's isolated we may want to enforce returning `json` from any API

**Comment by rokroskar** [comment]
@lorenzo-cavazzi is there an issue for that already?

**Comment by lorenzo-cavazzi** [comment]
Not yet, but if this is moving forward I can create the relevant issue and go through renku-notebooks to find all the functions that should change. This will probably require a coule of very quick fixes on the ui
