### ISSUE TITLE
Revive login mechanism for the renku CLI

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#199]
Everything needed for the Renku CLI to log into the gateway has been implemented a long time ago by @ebiiii. Unfortunately, the [corresponding PR](https://github.com/SwissDataScienceCenter/renku-python/pull/193) on renku-python has never been merged. With https://github.com/SwissDataScienceCenter/renku-graph/issues/300 coming up we have a use-case for this feature and we would like to complete its implementation. See https://github.com/SwissDataScienceCenter/renku-python/pull/1241.

On the gateway we should verify that the mechanism for a CLI login is still functional.

**Comment by rokroskar** [comment]
Maybe turn this into an epic?

**Comment by ableuler** [comment]
Closing as this has been completed.
