### ISSUE TITLE
Add automated dependency updates

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#205]
The python dependencies of this project should be updated automatically. Checkj the configuration on https://github.com/SwissDataScienceCenter/renku-notebooks as an example.

**Comment by rokroskar** [comment]
done - dependabot will spam this repo from now on as well. 🎉

**Comment by ableuler** [comment]
> done - dependabot will spam this repo from now on as well. 🎉

thanks!
