### ISSUE TITLE
Transition to black

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#206]
Using black auto-formatting would make this project look much cleaner and make it look more similar to other python-based Renku components.

**Comment by lorenzo-cavazzi** [comment]
Totally in favor!
But I believe [renku-python](https://github.com/SwissDataScienceCenter/renku-python) is not currently using black.

**Comment by rokroskar** [comment]
@lorenzo-cavazzi you are correct, but it will soon :)

**Comment by ableuler** [comment]
closed by #212.
