### ISSUE TITLE
Handle unicode characters in headers sent to core service

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-gateway#252]
Currently any user with a non-latin-1-encodable character in their full name will receive a 500 response from the gateway when trying to use any of core service APIs. The reason is that headers need to be latin-1 encodable. We should handle this appropriately in the gateway in one of two ways:

a) simply base64-encoding the headers 
b) putting the JWT itself (where this information comes from) into the header

Since the bug currently prevents users with non-latin-1 encodable characters, we should patch it asap with the simplest solution (a) and discuss whether it's worthwhile implementing solution (b).

**Comment by ableuler** [comment]
@rokroskar @lorenzo-cavazzi 
This has been closed by #253, right?

**Comment by rokroskar** [comment]
well partially - we haven't implemented the full solution (using the JWT directly) that's why it was kept open

**Comment by ableuler** [comment]
As discussed on [this issue](https://github.com/SwissDataScienceCenter/renku-python/issues/1414) the gateway should move the entire ID token of the user in a custom header.
