### ISSUE TITLE
Add gitlab oauth token to notebook-service requests

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#406]
The notebooks-service can not obtain gitlab tokens anymore once it's disconnected from JH and will need to get them from the gateway.

---

## Design suggestion
(_edit_)

It would be nice to take this issue as an example for a potential future header structure that all renku backend services would agree on. This would reduce the necessary forward-auth middlewares and remove a lot of almost-identical code in the gateway. Of course for accessing "off-the-shelf" backend services we still need an appropriate middleware to match the expected header structure on a case-by-case basis.

- All Renku backend service APIs receive the same headers fields in forwarded authenticated API requests.
- All Renku backend service APIs can trust those headers and rely on the fact that JWT signatures have been verified.
- Renku backend service APIs must not be exposed to the internet directly.
- Renku specific headers start with `Renku`, Renku-specific auth-related header start with `Renku-Auth`.
- All other headers (including the standard `Authorization: bearer <keycloak-access-token>` that clients use to authenticate their requests to the API gateway) will be stripped and not be forwarded to the backend service.
- Proposed headers:
```
Renku-Auth-Access-Token: <keycloak access token>
Renku-Auth-Id-Token: <keycloak id token>
Renku-Auth-Git-Credentials: <base64 encoded JSON object containing all GitLab/GitHub access credentials>
```
while the git credentials object would be something like this:
```
renkuAuthGitCredentials = {
  "https://renkulab.io/gitlab": {
    "provider: "GitLab",
    "AuthorizationHeader": "bearer <user gitlab oAuth2 token>"
  },
  "https://dev.renku.ch/gitlab": {
    "provider: "GitLab",
    "AuthorizationHeader": "token <user gitlab access token>"
  },
  "https://github.com":  {
    "provider: "GitHub",
    "AuthorizationHeader": "bearer <user github oauth token>"
  }
}
```
of course initially and as long as one RenkuLab instance can only connect to one GitLab instance, this JSON object would only have one entry.

**Comment by olevski** [comment]
This sounds good to me! I very much agree with making the traefik config file and in general the renku-gateway code shorter.

**Comment by rokroskar** [comment]
I think these headers are fine - what I would really like to see though is that in the auth implementation of the non-JH-based notebooks service this piece is modular. I.e. I want to make sure that "renku" bits and pieces are not hard-coded and can be swapped out for something more generic to make the service more broadly usable.
