### ISSUE TITLE
Investigate oauthlib update issues with Keycloak

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-gateway#441]
Following the [upgrade of oauthlib package](https://github.com/SwissDataScienceCenter/renku-gateway/pull/433), authentication does not work properly, we need to investigate and fix this issue.

**Comment by ableuler** [comment]
While this has already been tested on ci deployments, testing the upgrade on an already existing deployment which also includes a gitlab instance should reveal the error. I am not sure though that having a dedicated GitLab instance is a necessary condition for the error to appear.

**Comment by ableuler** [comment]
Could not reproduce this error, neither with new renku deployments nor with upgrades to existing ones. Even existing user sessions survive the upgrade of the gateway-auth component without any interruption. Should the problem appear on dev, we'll have to fix it there.
