### ISSUE TITLE
Refactor token handling

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#51]
Implement the server-side changes to match https://github.com/SwissDataScienceCenter/renku-ui/issues/307:

- [x] Set access tokens as secure HttpOnly cookies
- [x] Allow the access token to be sent as cookie header but enforce the presence of a custom header in this case to ensure the request was initiated by JS.
- [x] Check the Host/Referrer header and compare to the allowed origins specified in the access token
- [x] Properly set the Access-Control-Allow-Origin header

**Comment by rokroskar** [comment]
@ebiiii @ableuler if this is closed, does that mean the to-do list in the description is completed?

**Comment by ebiiii** [comment]
Well... the changes have been reverted, we may need to re-open this one to not forget to change it. 

@rokroskar yes, all items were addressed in the PR.
