### ISSUE TITLE
bug: passing in a JWT after logging out causes an exception

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-gateway#553]
To reproduce: 

1. Log in to renku, then obtain a JWT for the logged in user (e.g. via PKCE on the swagger page)
2. Log out of renku via the UI
3. try to access one of the `/api/renku` endpoints (e.g. https://dev.renku.ch/swagger/#/cache/get_renku_cache_files_list)
4. the gateway-auth service returns a 500 instead of handling the missing token properly

This is the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/code/app/__init__.py", line 170, in auth
    headers = auth.process(request, headers)
  File "/code/app/auth/renku_auth.py", line 45, in process
    headers["Renku-User"] = keycloak_oidc_client.token["id_token"]
AttributeError: 'NoneType' object has no attribute 'token'
```

A request with the same JWT token to `/api/user` works and returns the user info - it should instead indicate that the user is not logged in.

**Comment by olevski** [comment]
Another annoying this about this is that if you log into 2 different browsers (or even from 2 different computers) and then log out only from one the token in the redis db is gone. So even though you are still logged in in the other browser you cannot do much. Because the other browser will simply send requests to the gateway and the gateway will expect the token in redis to be there. But it will not be there.

**Comment by rokroskar** [comment]
Maybe we should use the JWT to check whether there are active sessions? There's probably a keycloak endpoint for that.

**Comment by olevski** [comment]
> Maybe we should use the JWT to check whether there are active sessions? There's probably a keycloak endpoint for that.

That is one way to do it. Another option is to set the key to expire after a certain amount of time. Redis supports this. And the nice thing is that if you do operations that target that key then the expiry timer will reset. So we can expire the tokens stored in redis after a day or two (or even more). And every time we try to access the token we check if it is there or not. If it is not there we get it and set the expiry time. Also with all of this when you log out the token in redis is not cleared. We just rely on the expiry time and on redis for the token to be eventually cleared.
