### ISSUE TITLE
Decide who has the knowledge about the webhook url (UI, gateway or Miner-service)

### ISSUE THREAD

**Issue by ebiiii** [SwissDataScienceCenter/renku-gateway#66]
And provide the corresponding endpoint in the gateway.

**Comment by rokroskar** [comment]
@jachro I'm pretty sure we have moved past this already -- could you please close if so, if not decide if it should be kept open?

**Comment by jachro** [comment]
Yes, that decision was taken and the callback URL is known only by `webhook-service` which manages hooks on behalf of Renku.
