### ISSUE TITLE
Realtime notifications to clients

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-gateway#8]
The proxy/gateway should give clients the possibility to subscribe to events. The API should be something like:

- create_notification_channel() : create a websocket for communication and return the url
- subscribe_to_event(notification_channel, event) : subscribe to events

The generate events, the proxy can initially use the gitlab web hooks. When notifications come in over the web hooks, these will be forwarded to the web socket.

See:
- https://pypi.org/project/websockets/
- https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#use-cases

**Comment by ebiiii** [comment]
switching to [Quart](https://pgjones.gitlab.io/quart/index.html) brings some additional capabilities to the gateway, like websocket ;-)  #50
