### ISSUE TITLE
Gateway to provide an API for exchanging user email to an oauth access token

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-gateway#82]
There's a need for backend services working independently to UI to have access to users' GitLab oauth tokens. As `renku-gateway` seems to be currently in charge of managing tokens, it sounds reasonable to create such an endpoint in that service.

### Proposal for the API

**GET `<renku-gateway-url>/oauth-tokens/{email}`**

**Headers:** `renku-graph-token -> <some token>`

**Response:**

- UNAUTHORIZED (401) if the `renku-graph-token` is absent or invalid
- OK (200) with the body: `{  oauth-token: "<user oauth token>" }`

### Considerations

This endpoint must be secured and accessible only to known services.

**Comment by ableuler** [comment]
@jachro There is no need for this anymore, right?
