### ISSUE TITLE
Use gitlab api wrapper

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#9]
For requests to gitlab we could rely on an existing python API wrapper: https://github.com/python-gitlab/python-gitlab
It seems to be actively maintained and brings things like paging through results for free.

**Comment by rokroskar** [comment]
Something to try out in parallel: https://docs.gitlab.com/ce/api/graphql/

**Comment by ableuler** [comment]
Closing since we are not coding any requests to gitlab anymore. Instead, treafik just forwards the requests.
